modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="tails"
version="1.20.1-1.0.0"
displayName="Tails"
description='''
        Tail Mode 1.20.1 Update
        Newer tail mode
    '''
authors="Kihira, Akashiro_Sku (1.20.1 port)"
displayURL="https://github.com/kihira"
logoFile="tails.png"

[[mods.dependencies.tails]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[mods.dependencies.tails]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"