@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package uk.kihira.tails.client;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;